llm:
  hub: ollama
  model: phi3
  api_url: http://localhost:11434

embedding:
  hub: ollama
  model: nomic-embed-text
  top_k: 3
  api_url: http://localhost:11434

vectorstore:
  database: chromadb
  path: chromadb
  name: documents

readers:
  enable_ocr: True
  chunk_size: 1024
  chunk_overlap: 256
